package com.avatarduel.event;

public enum EventType {
    SUMMON, ATTACHSKILL, DISCARDHAND, DISCARDFIELD, CHANGESTANCE, SUMMONSUCCESS, SUMMONFAIL, SUMMONFAILBUTENOUGHPOWER, ALREADYSUMMONEDLAND, ATTACK;
}
